name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          load: true
          push: false
          tags: podman/build:latest
          build-args: |
            PODMAN_VERSION=4.4.2
      -
        name: fetch artifact
        run: |
          docker cp $(docker create --name tc podman/build:latest):/podman-4.4.2/bin ./podman && docker rm tc
          tar -czf podman.tar.xz -C podman *
          sha256sum podman.tar.xz | awk '{ print $1 }' > podman.tar.xz.sha256
      -
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podman.tar.xz
            podman.tar.xz.sha256
