name: ci

on: push

env:
  PODMAN_VERSION: 5.0.1
  CONMON_VERSION: 2.1.10

jobs:
  debian11:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: podman/build:latest
          build-args: |
            PODMAN_VERSION=${{ env.PODMAN_VERSION }}
            CONMON_VERSION=${{ env.CONMON_VERSION }}
            DEBIAN=11
      -
        name: fetch artifact
        run: |
          docker cp $(docker create --name tc podman/build:latest):/podman-${PODMAN_VERSION}/bin ./podman && docker rm tc
          tar -czf podman-deb11.tar.gz -C podman podman podman-remote quadlet rootlessport
          sha256sum podman-deb11.tar.gz | awk '{ print $1 }' > podman-deb11.tar.gz.sha256
          docker cp $(docker create --name tc podman/build:latest):/conmon-${CONMON_VERSION}/bin/conmon . && docker rm tc
          tar -czf conmon-deb11.tar.gz conmon
          sha256sum conmon-deb11.tar.gz | awk '{ print $1 }' > conmon-deb11.tar.gz.sha256
      -
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podman-deb11.tar.gz
            podman-deb11.tar.gz.sha256
            conmon-deb11.tar.gz
            conmon-deb11.tar.gz.sha256
  debian12:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: podman/build:latest
          build-args: |
            PODMAN_VERSION=${{ env.PODMAN_VERSION }}
            CONMON_VERSION=${{ env.CONMON_VERSION }}
            DEBIAN=12
      -
        name: fetch artifact
        run: |
          docker cp $(docker create --name tc podman/build:latest):/podman-${PODMAN_VERSION}/bin ./podman && docker rm tc
          tar -czf podman-deb12.tar.gz -C podman podman podman-remote quadlet rootlessport
          sha256sum podman-deb12.tar.gz | awk '{ print $1 }' > podman-deb12.tar.gz.sha256
          docker cp $(docker create --name tc podman/build:latest):/conmon-${CONMON_VERSION}/bin/conmon . && docker rm tc
          tar -czf conmon-deb12.tar.gz conmon
          sha256sum conmon-deb12.tar.gz | awk '{ print $1 }' > conmon-deb12.tar.gz.sha256
      -
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podman-deb12.tar.gz
            podman-deb12.tar.gz.sha256
            conmon-deb12.tar.gz
            conmon-deb12.tar.gz.sha256
